### ISSUE TITLE
Wrong response from Etherscan or wrong Contract Address

### ISSUE THREAD

**Issue by donaldduckcheshta** [Neufund/smart-contract-watch#69]
Using correct contract address , still doesn't able to know why landing into below issue . 

Please find below exact snipped i am getting on running yarn command 

yarn start -f latest -a 0x12bb5aaC86e2971dBA217cEd3DCdc284d3D44cA2 -n "http://localhost:8545" -l "info" -q

$ ./node_modules/.bin/babel  ./src --experimental --source-maps-inline -d ./dist && node ./dist  -f latest -a 0x12bb5aaC86e2971dBA217cEd3DCdc284d3D44cA2 -n http://localhost:8545 -l info -q
src/command.js -> dist/command.js
src/config.js -> dist/config.js
src/decoder.js -> dist/decoder.js
src/etherscan.js -> dist/etherscan.js
src/index.js -> dist/index.js
src/jsonrpc.js -> dist/jsonrpc.js
src/logger.js -> dist/logger.js
src/output/graylogFormat.js -> dist/output/graylogFormat.js
src/output/index.js -> dist/output/index.js
src/output/terminalFormat.js -> dist/output/terminalFormat.js
src/utils.js -> dist/utils.js
src/web3/customRpc.js -> dist/web3/customRpc.js
src/web3/utils.js -> dist/web3/utils.js
src/web3/web3Provider.js -> dist/web3/web3Provider.js

Wrong response from Etherscan or wrong Contract Address
Error: Wrong response from Etherscan or wrong Contract Address
    at validateResponse (/home/cheshta/Documents/smart-contract-watch-master/dist/etherscan.js:53:9)
    at /home/cheshta/Documents/smart-contract-watch-master/dist/etherscan.js:87:5
    at next (native)
    at step (/home/cheshta/Documents/smart-contract-watch-master/dist/etherscan.js:28:191)
    at /home/cheshta/Documents/smart-contract-watch-master/dist/etherscan.js:28:361
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c ./node_modules/.bin/babel  ./src --experimental --source-maps-inline -d ./dist && node ./dist  -f latest -a 0x12bb5aaC86e2971dBA217cEd3DCdc284d3D44cA2 -n http://localhost:8545 -l info -q
Directory: /home/cheshta/Documents/smart-contract-watch-master
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/cheshta/Documents/smart-contract-watch-master/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Kindly confirm on above issue

**Comment by Moejoe90** [comment]
Have you tried checking this address on etherscan? Its not verified so you will have to somehow provide the ABI manually

**Comment by donaldduckcheshta** [comment]
ahh okay . Yes , address is not verified. 
Please suggest how to provide ABI manually ?

I am using below command to get event logs :-    
yarn start -f latest -a 0x12bb5aaC86e2971dBA217cEd3DCdc284d3D44cA2 -n "http://localhost:8545" -l "info" -q

**Comment by Moejoe90** [comment]
You will have to have the smartcontracts ABI copy it to the contracts folder with `address.json` if you don't have the ABI then i'm afraid there is not much to do

**Comment by Moejoe90** [comment]
I will close this issue now
